# Generated by Django 4.2.1 on 2026-09-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('seed', models.BigIntegerField(blank=True, help_text='Re-running with the same seed and settings reproduces the dataset.', null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Exact generator settings used for this run.')),
                ('counts', models.JSONField(blank=True, default=dict, help_text='Rows written, per model.')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DELETING', 'Deleting')], db_index=True, default='RUNNING', max_length=15)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('include_dirty_data', models.BooleanField(default=False)),
                ('progress_stage', models.CharField(blank=True, max_length=40)),
                ('progress_users', models.PositiveIntegerField(default=0)),
                ('progress_orders', models.PositiveIntegerField(default=0)),
                ('target_users', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'test data batch',
                'verbose_name_plural': 'test data batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
