"""Demo catalog for Sondermark Coffee Roasters (a fictional brand).

Photography: free Unsplash images (see docs/images.md for the credits). Only the photo id is stored here;
`unsplash()` builds a sized URL and templates re-size it for cards.
"""


def unsplash(photo_id, w=1200):
    return f"https://images.unsplash.com/{photo_id}?auto=format&fit=crop&w={w}&q=75"


# slug -> (name, description, position, image id)
CATEGORIES = [
    ("filter-coffee", "Filter Coffee", "Single-origin lots roasted light to medium for pour-over, AeroPress and batch brewers.", 1, "photo-1545665225-b23b99e4d45e"),
    ("espresso", "Espresso", "Blends and single origins developed a touch further for syrupy shots and milk drinks.", 2, "photo-1649882453801-d5f84502c3f0"),
    ("decaf", "Decaf", "Properly good decaf — sugarcane and Swiss Water processed, roasted like our caffeinated coffees.", 3, "photo-1508088405209-fbd63b6a4f50"),
    ("drip-bags-gifts", "Gifts & Drip Bags", "Single-serve drip bags, tasting sets and gift boxes ready to wrap.", 4, "photo-1643427517196-7822b972517f"),
    ("subscriptions", "Subscriptions", "Fresh coffee on your schedule. Pause, skip or switch any time.", 5, "photo-1748895177768-b4a54b9c2954"),
    ("equipment", "Equipment", "Drippers, servers, grinders, kettles and mugs we use on our own brew bar.", 6, "photo-1621745147794-843ab24c3b05"),
]

BRANDS = [
    ("sondermark", "Sondermark", "Our own roastery label — every coffee we roast in Valencia."),
    ("tolva", "Tolva Brewware", "Simple, well-made pour-over tools designed in Lisbon."),
    ("norrgrind", "Norrgrind", "Burr grinders built for home baristas who care about consistency."),
    ("kiln-clay", "Kiln & Clay", "Hand-glazed stoneware from a small workshop in Girona."),
]

COFFEE_VARIANTS = [  # suffix, name, price multiplier, attributes
    ("250W", "250 g · Whole bean", 1, {"weight_g": 250, "grind": "whole"}),
    ("250G", "250 g · Ground", 1, {"weight_g": 250, "grind": "ground"}),
    ("1KGW", "1 kg · Whole bean", 3.4, {"weight_g": 1000, "grind": "whole"}),
]

PRODUCTS = [
    # ------------------------------------------------------------------ filter coffee
    {
        "sku": "SM-ETH-SID", "name": "Ethiopia Sidamo Bensa", "category": "filter-coffee", "kind": "COFFEE", "featured": True,
        "short": "A washed Sidamo that tastes like jasmine tea with a peachy finish.",
        "price": "14.50", "cost": "6.90", "stock": 140,
        "origin": "Ethiopia", "region": "Sidamo, Bensa", "producer": "Bensa Daye washing station", "variety": "Heirloom (74110, 74112)",
        "process": "WASHED", "roast": "LIGHT", "altitude": "2,050–2,250 m", "notes": "Jasmine, bergamot, peach",
        "brew": "v60,chemex,aeropress,batch",
        "description": "Our longest-standing Ethiopian relationship. The Bensa Daye station sits high in Sidamo, where smallholders deliver ripe cherry that is fermented for 48 hours, washed in spring water and dried slowly on raised beds. We roast it light to keep the florals intact: expect a tea-like body, bright bergamot acidity and a long, sweet peach finish as it cools.",
        "highlights": ["Floral and delicate — the coffee people mean when they say 'it doesn't taste like coffee'", "Roasted light to preserve origin character", "Fully traceable to one washing station", "Best enjoyed black, as a pour-over"],
        "brew_guide": ["Grind 15 g medium-fine (like table salt) for a V60 02.", "Rinse the filter and heat 250 g of water to 94 °C.", "Bloom with 45 g for 40 seconds, stirring gently.", "Pour to 150 g by 1:15, then to 250 g by 2:00 in slow circles.", "Aim for a total brew time of 2:45–3:15. Let it cool a little before tasting."],
        "story": "Sidamo is the birthplace of Arabica, and Bensa sits at its highest, coolest edge. Cherries ripen slowly up here, building the dense sugars that give the coffee its perfume. We have bought from Bensa Daye every year since 2019 and pay a fixed premium over the ECX price so the station can keep investing in drying beds and water recycling.",
        "story_image": "photo-1515694590185-73647ba02c10",
        "images": [("photo-1695245503558-5cdb37f49092", "Kraft coffee bag of Ethiopia Sidamo Bensa"), ("photo-1517224187585-e3016a5fddc8", "Pouring water over a V60 filter"), ("photo-1692299116305-762729f2e9d5", "Light roasted coffee beans")],
    },
    {
        "sku": "SM-COL-HUI", "name": "Colombia Huila El Diviso", "category": "filter-coffee", "kind": "COFFEE", "featured": True,
        "short": "Sweet, balanced and endlessly drinkable — red apple, caramel and milk chocolate.",
        "price": "13.00", "compare_at": "14.50", "cost": "6.10", "stock": 210,
        "origin": "Colombia", "region": "Huila, Pitalito", "producer": "Finca El Diviso — Nestor Lasso", "variety": "Caturra, Colombia",
        "process": "WASHED", "roast": "MEDIUM_LIGHT", "altitude": "1,750–1,900 m", "notes": "Red apple, caramel, milk chocolate",
        "brew": "v60,aeropress,french_press,batch",
        "description": "The coffee we reach for every morning. El Diviso is a family farm above Pitalito where the Lasso brothers ferment their washed lots a little longer than their neighbours, which gives this coffee its juicy apple acidity. A medium-light roast rounds it out with caramel sweetness and a soft milk-chocolate finish. Forgiving in every brewer.",
        "highlights": ["Balanced and sweet — a crowd-pleaser for guests", "Works in pour-over, AeroPress and the office batch brewer", "Direct relationship with the Lasso family since 2021", "Great value: our best-selling single origin"],
        "brew_guide": ["Grind 16 g medium for a V60 or flat-bottom dripper.", "Heat 260 g of water to 93 °C.", "Bloom with 50 g for 35 seconds.", "Pour in two further stages to 260 g, finishing pouring by 1:45.", "Target a drawdown of around 2:45. Serve."],
        "story": "Huila's steep hillsides produce some of Colombia's most expressive washed coffees. At El Diviso, cherries are floated, de-pulped and fermented for 36 hours before being washed and dried under shade. We taste the harvest with Nestor every February and pick the lots for this blend of tables ourselves.",
        "story_image": "photo-1633437805600-2c58bf56663c",
        "images": [("photo-1669296667524-906d519cbe3e", "Open kraft bag with coffee beans spilling out"), ("photo-1545665225-b23b99e4d45e", "Pour-over brewing into a glass server"), ("photo-1442550528053-c431ecb55509", "Roasted coffee beans close-up")],
    },
    {
        "sku": "SM-KEN-NYE", "age_days": 5, "name": "Kenya Nyeri AA Gatomboya", "category": "filter-coffee", "kind": "COFFEE", "featured": False,
        "short": "Classic Nyeri intensity: blackcurrant, pink grapefruit and brown sugar.",
        "price": "16.90", "cost": "8.40", "stock": 6,
        "origin": "Kenya", "region": "Nyeri", "producer": "Gatomboya Factory, Barichu FCS", "variety": "SL28, SL34, Ruiru 11",
        "process": "WASHED", "roast": "LIGHT", "altitude": "1,800–1,950 m", "notes": "Blackcurrant, pink grapefruit, brown sugar",
        "brew": "v60,chemex,aeropress",
        "description": "Only a few bags left of this year's lot. Gatomboya is a factory (washing station) of the Barichu cooperative, famous for the double-fermented, spring-washed style that makes Nyeri coffees so vivid. AA screen size, SL28-led, roasted light: intensely juicy blackcurrant, grapefruit acidity and a brown-sugar sweetness that lingers.",
        "highlights": ["Big, juicy acidity — the most intense coffee on our shelf", "AA grade, SL28-led lot from a celebrated factory", "Limited: one pallet per harvest", "Spectacular as a Chemex for two"],
        "brew_guide": ["Grind 20 g medium-coarse for a Chemex 6-cup.", "Heat 330 g of water to 95 °C.", "Bloom with 60 g for 45 seconds.", "Pour in slow spirals to 330 g by 2:15.", "Expect a drawdown of around 4:00. Swirl the carafe before serving."],
        "story": "Kenya's cooperative system means each factory processes cherry from hundreds of neighbouring smallholders. Gatomboya sits on the slopes of the Aberdare range, using cold mountain water for its two-stage fermentation and a long soak that sharpens the coffee's signature acidity.",
        "story_image": "photo-1663125365404-e274869480f6",
        "images": [("photo-1661669037570-72efa689b68d", "Silver coffee bag standing among green plants"), ("photo-1748894851733-be6747a9c061", "Ground coffee in a V60 ready for brewing"), ("photo-1513530176992-0cf39c4cbed4", "Scattered roasted coffee beans")],
    },
    {
        "sku": "SM-GUA-HUE", "name": "Guatemala Huehuetenango La Bolsa", "category": "filter-coffee", "kind": "COFFEE", "featured": False,
        "short": "Orange zest, toffee and cocoa — the friendly all-rounder of the range.",
        "price": "12.80", "cost": "6.00", "stock": 95,
        "origin": "Guatemala", "region": "Huehuetenango, La Libertad", "producer": "Finca La Bolsa — Vides family", "variety": "Bourbon, Caturra",
        "process": "WASHED", "roast": "MEDIUM", "altitude": "1,400–1,700 m", "notes": "Orange zest, toffee, cocoa",
        "brew": "v60,french_press,aeropress,moka,batch",
        "description": "Huehuetenango's dry, warm winds off the Mexican plains let coffee dry slowly and evenly, and La Bolsa has been making the most of them since 1958. We roast this lot medium: a round body, gentle orange acidity, toffee sweetness and a cocoa finish. A coffee that suits every brewer and a splash of milk.",
        "highlights": ["Medium roast that suits filter, press and moka alike", "Rainforest Alliance certified family farm", "Comforting and sweet, low in sharp acidity", "Our pick for a first step into specialty coffee"],
        "brew_guide": ["Grind 30 g coarse for a 500 ml French press.", "Add 500 g of water at 94 °C and stir once.", "Steep for 4 minutes, then break and skim the crust.", "Wait 4 more minutes, then press gently and decant fully."],
        "story": "La Bolsa sits in a protected valley at the foot of the Cuchumatanes mountains. The Vides family has farmed it for three generations and runs a school and clinic for the picking crews who arrive each January. It is one of the first farms we ever bought from.",
        "story_image": "photo-1647220577886-6a5faaa7c141",
        "images": [("photo-1509785307050-d4066910ec1e", "Roasted coffee beans beside a cup of coffee"), ("photo-1530346460498-48afc564f57a", "Chemex brewer and cup on a table")],
    },
    {
        "sku": "SM-CRI-TAR", "age_days": 9, "name": "Costa Rica Tarrazú Honey", "category": "filter-coffee", "kind": "COFFEE", "featured": True,
        "short": "A red-honey lot with real honey sweetness, red grape and almond.",
        "price": "14.20", "cost": "6.80", "stock": 120,
        "origin": "Costa Rica", "region": "Tarrazú, San Marcos", "producer": "Micro-mill La Casona", "variety": "Catuaí, Villa Sarchí",
        "process": "HONEY", "roast": "MEDIUM_LIGHT", "altitude": "1,650–1,800 m", "notes": "Honey, red grape, almond",
        "brew": "v60,aeropress,chemex,cold_brew",
        "description": "Honey processing leaves part of the fruit mucilage on the bean while it dries, and you can taste it: syrupy sweetness, soft red-grape acidity and an almond finish. La Casona is a family micro-mill in the heart of Tarrazú that we have visited twice; this is their red-honey Catuaí lot, roasted medium-light.",
        "highlights": ["Syrupy sweetness from red-honey processing", "Lovely as cold brew in summer", "Micro-mill lot with full traceability", "Balanced enough for first-time pour-over"],
        "brew_guide": ["Grind 17 g medium for an AeroPress (standard).", "Add 230 g of water at 90 °C and stir 3 times.", "Steep for 1:30, place the cap and press slowly for 30 seconds.", "Dilute to taste — it is lovely as it is."],
        "story": "Tarrazú's volcanic soils and distinct dry season make it ideal for honey processing, where drying must be slow but never interrupted. La Casona turns the parchment by hand every hour for up to three weeks. The result is one of the sweetest coffees we roast.",
        "story_image": "photo-1629008642899-178df6fc5f2f",
        "images": [("photo-1615380547241-75c51aad004e", "Kraft coffee bags with red seals"), ("photo-1472495010058-65576a9959e4", "Hand holding ripe coffee cherries"), ("photo-1545665613-29394cee622b", "V60 pour-over on a glass server")],
    },
    {
        "sku": "SM-RWA-NYA", "age_days": 16, "name": "Rwanda Nyamasheke Kanzu", "category": "filter-coffee", "kind": "COFFEE", "featured": False,
        "short": "Elegant and floral with red berries and a black-tea finish.",
        "price": "13.90", "cost": "6.50", "stock": 80,
        "origin": "Rwanda", "region": "Nyamasheke, Western Province", "producer": "Kanzu washing station", "variety": "Red Bourbon",
        "process": "WASHED", "roast": "LIGHT", "altitude": "1,900–2,100 m", "notes": "Red berries, orange blossom, black tea",
        "brew": "v60,chemex,aeropress,batch",
        "description": "Kanzu sits above Lake Kivu where Red Bourbon trees grow on steep terraces. The station's meticulous sorting and long fermentation produce a clean, elegant cup: red berries, orange blossom and a black-tea structure that makes it perfect for a slow Sunday pour-over.",
        "highlights": ["Clean, elegant and floral", "100% Red Bourbon from terraced smallholdings", "Supports the Kanzu women's producer group", "Lovely with breakfast pastries"],
        "brew_guide": ["Grind 15 g medium-fine for a V60 01.", "Heat 250 g of water to 94 °C.", "Bloom with 40 g for 30 seconds.", "Pour steadily to 250 g by 1:45.", "Total time 2:30–3:00."],
        "story": "Rwanda's coffee sector was rebuilt around washing stations like Kanzu, which now pays second-harvest premiums back to its 700 member farmers. We buy one lot each season, chosen blind on the cupping table.",
        "story_image": "photo-1626402679707-b248aa61e5ff",
        "images": [("photo-1536227661368-deef57acf708", "Cup of black coffee surrounded by beans"), ("photo-1597341510440-5b82f96e6dcf", "Pouring coffee into a black ceramic mug")],
    },
    {
        "sku": "SM-BRA-CER", "name": "Brazil Cerrado Santa Inês Natural", "category": "filter-coffee", "kind": "COFFEE", "featured": False,
        "short": "Hazelnut, milk chocolate and dried fig — comfort in a cup, and a great espresso too.",
        "price": "11.50", "cost": "5.20", "stock": 260,
        "origin": "Brazil", "region": "Cerrado Mineiro", "producer": "Fazenda Santa Inês", "variety": "Yellow Catuaí, Mundo Novo",
        "process": "NATURAL", "roast": "MEDIUM", "altitude": "1,100–1,250 m", "notes": "Hazelnut, milk chocolate, dried fig",
        "brew": "french_press,moka,espresso,batch,cold_brew",
        "description": "Sun-dried on patios in the Cerrado's reliable dry season, this natural Catuaí is all about sweetness and body. Roasted medium it gives hazelnut, milk chocolate and a dried-fig fruitiness with very little acidity — a comfort coffee that also pulls a lovely, classic espresso.",
        "highlights": ["Low acidity, heavy body, big sweetness", "Equally good as filter, moka or espresso", "Best value coffee in the range", "Naturally processed on a Rainforest Alliance certified estate"],
        "brew_guide": ["Grind 18 g fine for a 3-cup moka pot.", "Fill the base with water just below the valve, pre-heated to 70 °C.", "Fill the basket loosely without tamping.", "Brew on medium heat with the lid open; remove at the first sputter.", "Serve immediately, ideally with a little warm milk."],
        "story": "Santa Inês is a fourth-generation estate on the Cerrado plateau with its own drying patios, school and nursery. Its consistent naturals are the backbone of our espresso blends, and this lot was good enough to bottle on its own.",
        "story_image": "photo-1701735513192-bc7248978c51",
        "images": [("photo-1565273975921-c884f2b703df", "Jute sacks of Brazilian green coffee"), ("photo-1607681034540-2c46cc71896d", "Stirring roasted coffee beans with a scoop"), ("photo-1580933073521-dc49ac0d4e6a", "Roasted coffee beans on a wooden table")],
    },
    # ------------------------------------------------------------------ espresso
    {
        "sku": "SM-ESP-MRG", "name": "Morning Ridge Espresso Blend", "category": "espresso", "kind": "COFFEE", "featured": True,
        "short": "Our house espresso: chocolate, hazelnut and caramel that shines through milk.",
        "price": "12.50", "cost": "5.60", "stock": 320,
        "origin": "Brazil, Colombia", "region": "Cerrado Mineiro & Huila", "producer": "Fazenda Santa Inês · El Diviso", "variety": "Catuaí, Caturra",
        "process": "NATURAL", "roast": "MEDIUM", "altitude": "1,100–1,900 m", "notes": "Dark chocolate, hazelnut, caramel",
        "brew": "espresso,moka,french_press",
        "description": "Seventy percent Brazilian natural for body and sweetness, thirty percent washed Colombian for a lift of red-apple acidity. Roasted medium and rested for ten days before shipping, Morning Ridge pulls a syrupy, chocolatey shot that stays sweet in a flat white. It is the blend on our own bar every day.",
        "highlights": ["Forgiving to dial in on home machines", "Built to cut through milk without bitterness", "Consistent all year — components change, the profile does not", "Our best-selling coffee, full stop"],
        "brew_guide": ["Dose 18 g into a double basket, ground fine.", "Aim for 38–40 g of espresso in 27–32 seconds.", "Brew at 93 °C. If it runs fast and sour, grind finer; slow and bitter, grind coarser.", "Rested 10–30 days off roast is the sweet spot."],
        "story": "We designed Morning Ridge in 2018 for the cafés we supply, then realised it was exactly what people wanted at home. The Brazilian base comes from Santa Inês in the Cerrado; the Colombian component rotates between our Huila partners through the year.",
        "story_image": "photo-1741994043738-393513f7bf52",
        "images": [("photo-1712402832925-d41c446883d3", "Brown coffee bag next to a cup of coffee"), ("photo-1510591509098-f4fdc6d0ff04", "Espresso with crema in a white cup"), ("photo-1627902511858-6ad7e004fd35", "Espresso machine pulling a shot")],
    },
    {
        "sku": "SM-ESP-MDH", "name": "Midnight Harbour Dark Espresso", "category": "espresso", "kind": "COFFEE", "featured": False,
        "short": "Our darkest roast: bittersweet chocolate, molasses and walnut. Still clean, never ashy.",
        "price": "11.90", "cost": "5.30", "stock": 180,
        "origin": "Brazil, India", "region": "Cerrado Mineiro & Chikmagalur", "producer": "Fazenda Santa Inês · Kelagur Estate", "variety": "Catuaí, S795",
        "process": "NATURAL", "roast": "MEDIUM_DARK", "altitude": "1,100–1,400 m", "notes": "Bittersweet chocolate, molasses, walnut",
        "brew": "espresso,moka,french_press,cold_brew",
        "description": "For people who like their espresso dark but hate the burnt taste of supermarket beans. A Brazilian natural and a washed Indian Arabica roasted medium-dark for heavy body and bittersweet chocolate, with a long molasses finish. Excellent in a moka pot or as a strong cold brew.",
        "highlights": ["Traditional strength without the ash", "Made for milk: big body, low acidity", "Excellent moka pot and cold-brew coffee", "Rested for 14 days before it ships"],
        "brew_guide": ["Dose 18 g ground fine.", "Aim for 36 g in 25–28 seconds at 92 °C.", "For moka: grind fine, medium heat, stop at the first gurgle."],
        "story": "Kelagur Estate in Chikmagalur grows shade coffee among pepper vines and silver oak, giving a spicy, heavy-bodied Arabica that stands up beautifully to a darker roast.",
        "story_image": "photo-1741993677051-29ffdc7c6830",
        "images": [("photo-1661669037616-4e78ad5dfbfb", "Black coffee bag with a label"), ("photo-1601390483714-955fd3066695", "Espresso in a glass"), ("photo-1641759677597-15b2422bc0e8", "Espresso extracting into a cup")],
    },
    {
        "sku": "SM-ESP-BRH", "age_days": 20, "name": "Bright Hour Seasonal Espresso", "category": "espresso", "kind": "COFFEE", "featured": False,
        "short": "A fruit-forward seasonal espresso: strawberry, milk chocolate and florals.",
        "price": "15.50", "cost": "7.30", "stock": 0,
        "origin": "Ethiopia", "region": "Guji, Hambela", "producer": "Buku Sayisa", "variety": "Heirloom",
        "process": "NATURAL", "roast": "MEDIUM_LIGHT", "altitude": "2,100–2,300 m", "notes": "Strawberry, milk chocolate, rose",
        "brew": "espresso,aeropress",
        "description": "Each season we pick one coffee to roast as a lighter, fruit-forward espresso. This summer it is a natural Guji from Buku Sayisa: strawberry jam, milk chocolate and a rosy aroma. Sold out for now — the next lot lands in September.",
        "highlights": ["Limited seasonal release", "Fruit-forward modern espresso", "Outstanding as a long black", "Next lot lands in September — join the newsletter"],
        "brew_guide": ["Dose 18 g, grind a touch coarser than a classic blend.", "Aim for 42 g in 28–32 seconds at 94 °C.", "Try it as a 1:2.5 ratio for clarity."],
        "story": "Hambela's high plateaus produce some of Ethiopia's most fruit-driven naturals. Buku Sayisa dries whole cherries on raised beds for up to 25 days, turning them constantly to build that jammy strawberry note.",
        "story_image": "photo-1677125671399-65852c6dfb05",
        "images": [("photo-1630595478342-5b257b95f783", "Kraft coffee bag and mug beside an espresso machine"), ("photo-1558416165-5fb04b79b0e7", "Espresso shots pouring into two cups")],
    },
    {
        "sku": "SM-ETH-GUJ", "age_days": 12, "name": "Ethiopia Guji Natural Espresso", "category": "espresso", "kind": "COFFEE", "featured": False,
        "short": "Single-origin espresso: blueberry, cocoa nibs and a wine-like finish.",
        "price": "15.90", "cost": "7.40", "stock": 60,
        "origin": "Ethiopia", "region": "Guji, Uraga", "producer": "Uraga Raro station", "variety": "Heirloom",
        "process": "NATURAL", "roast": "MEDIUM", "altitude": "2,000–2,200 m", "notes": "Blueberry, cocoa nibs, red wine",
        "brew": "espresso,moka,aeropress",
        "description": "The natural Guji that converted our espresso sceptics. Roasted a shade darker than our filter Ethiopians to tame the acidity, it delivers unmistakable blueberry, a cocoa-nib bitterness and a winey, lingering finish. A single-origin espresso with real personality.",
        "highlights": ["Blueberry-bomb natural process", "Roasted specifically for espresso", "Great as an Americano or long black", "Small station lot, 20 bags per year"],
        "brew_guide": ["Dose 18 g fine.", "Aim for 40 g in 28–30 seconds at 93 °C.", "Let it cool slightly — the fruit comes forward."],
        "story": "Uraga sits at the top of Guji's Raro valley. The station dries cherries for three weeks under shade nets, which slows fermentation and keeps the fruit notes clean rather than boozy.",
        "story_image": "photo-1626402679707-b248aa61e5ff",
        "images": [("photo-1610889556528-9a770e32642f", "Espresso in a glass cup on a saucer"), ("photo-1447933601403-0c6688de566e", "Roasted coffee beans close-up")],
    },
    # ------------------------------------------------------------------ decaf
    {
        "sku": "SM-COL-DEC", "name": "Colombia Decaf Sugarcane EA", "category": "decaf", "kind": "COFFEE", "featured": True,
        "short": "Decaf that tastes like coffee: toffee, red apple and cocoa, evening-friendly.",
        "price": "13.50", "cost": "6.40", "stock": 150,
        "origin": "Colombia", "region": "Huila & Tolima", "producer": "Descafecol, Manizales", "variety": "Caturra, Castillo",
        "process": "DECAF_EA", "roast": "MEDIUM", "altitude": "1,600–1,900 m", "notes": "Toffee, red apple, cocoa",
        "brew": "v60,espresso,aeropress,french_press,moka",
        "description": "Decaffeinated in Colombia with ethyl acetate derived from sugarcane — a gentle, natural process that keeps the coffee's sweetness intact. Roasted medium, it gives toffee, a soft red-apple acidity and a cocoa finish. Works equally well as a pour-over at 9 pm or as the second espresso of the afternoon.",
        "highlights": ["Sugarcane EA process keeps flavour, removes 99.9% of caffeine", "Roasted exactly like our regular Colombian", "Works in every brewer, including espresso", "Decaffeinated close to the farms, in Colombia"],
        "brew_guide": ["Grind 16 g medium for a V60.", "Heat 260 g of water to 92 °C — decaf likes it a touch cooler.", "Bloom with 45 g for 30 seconds, then pour to 260 g by 1:45.", "Total time around 2:45."],
        "story": "Descafecol in Manizales uses naturally fermented sugarcane to produce the ethyl acetate that lifts caffeine out of green coffee. Because it happens in Colombia, the coffee travels fresh and the value stays in the country of origin.",
        "story_image": "photo-1613399421011-1e634fa4dacc",
        "images": [("photo-1666873903780-396269c73a54", "Tin of roasted coffee beans seen from above"), ("photo-1553742198-6eea5ac42a24", "White cup of espresso on a saucer")],
    },
    {
        "sku": "SM-MEX-DEC", "name": "Mexico Chiapas Decaf Swiss Water", "category": "decaf", "kind": "COFFEE", "featured": False,
        "short": "Chemical-free Swiss Water decaf: milk chocolate, roasted nuts and a soft finish.",
        "price": "13.00", "compare_at": "14.00", "cost": "6.20", "stock": 90,
        "origin": "Mexico", "region": "Chiapas, Sierra Madre", "producer": "Cooperative Triunfo Verde", "variety": "Typica, Bourbon",
        "process": "DECAF_SWP", "roast": "MEDIUM_DARK", "altitude": "1,300–1,600 m", "notes": "Milk chocolate, roasted nuts, brown sugar",
        "brew": "espresso,moka,french_press,cold_brew",
        "description": "A certified organic Chiapas lot decaffeinated with nothing but water, time and carbon filters. Roasted medium-dark for a round, nutty cup with milk-chocolate sweetness and no sharp edges. Our decaf of choice for milk drinks and moka pots.",
        "highlights": ["Swiss Water process — no solvents", "Organic cooperative coffee", "Medium-dark roast made for milk", "Friendly in a French press"],
        "brew_guide": ["Grind 18 g fine for espresso and aim for 38 g in 28 seconds.", "For French press, 30 g coarse in 500 g water, 4 minutes."],
        "story": "Triunfo Verde's 400 members farm organic shade coffee on the slopes of the El Triunfo biosphere reserve, one of the last cloud forests in Mexico.",
        "story_image": "photo-1647220577886-6a5faaa7c141",
        "images": [("photo-1508088405209-fbd63b6a4f50", "Espresso cup with spoon on a white table"), ("photo-1442550528053-c431ecb55509", "Roasted coffee beans")],
    },
    # ------------------------------------------------------------------ drip bags & gifts
    {
        "sku": "SM-DRP-BOX", "name": "Drip Bag Box — Colombia Huila (10 × 12 g)", "category": "drip-bags-gifts", "kind": "COFFEE", "featured": True,
        "short": "Specialty coffee anywhere: ten single-serve drip bags of our Colombian, just add hot water.",
        "price": "16.00", "cost": "7.00", "stock": 130,
        "origin": "Colombia", "region": "Huila, Pitalito", "producer": "Finca El Diviso", "variety": "Caturra, Colombia",
        "process": "WASHED", "roast": "MEDIUM_LIGHT", "altitude": "1,750–1,900 m", "notes": "Red apple, caramel, milk chocolate",
        "brew": "v60",
        "description": "Each nitrogen-flushed sachet holds 12 g of freshly ground Colombia Huila El Diviso in a paper filter that hangs over any mug. No grinder, no equipment — just water at around 92 °C and three minutes. Perfect for the office, hotels, trains and camping.",
        "highlights": ["Ten individually sealed, nitrogen-flushed bags", "Same coffee as our best-selling single origin", "No equipment needed — fits any mug", "Compostable filter, recyclable outer sachet"],
        "brew_guide": ["Tear open the sachet and hook the paper ears over your mug.", "Pour 30 g of water just off the boil and wait 30 seconds.", "Pour in 3–4 stages up to about 180 g.", "Remove the bag once it has finished dripping, around 3 minutes."],
        "story": "We built the drip-bag line for our own travel bags before customers started asking for it. Every box is packed within 24 hours of grinding.",
        "story_image": "photo-1643427517196-7822b972517f",
        "images": [("photo-1643427517196-7822b972517f", "Pouring water into a drip coffee bag hanging over a glass"), ("photo-1749137997054-d556a40051aa", "Drip bag coffee brewing in a glass cup")],
        "variants": [("10", "Box of 10", 1, {"bags": 10}), ("30", "Box of 30", 2.7, {"bags": 30})],
    },
    {
        "sku": "SM-GFT-TRIO", "name": "Discovery Trio Gift Box", "category": "drip-bags-gifts", "kind": "BUNDLE", "featured": True,
        "short": "Three 100 g bags — Ethiopia, Colombia and Brazil — with a tasting card. The perfect introduction.",
        "price": "24.90", "compare_at": "29.90", "cost": "11.00", "stock": 75,
        "origin": "Ethiopia, Colombia, Brazil", "region": "", "producer": "", "variety": "",
        "process": "", "roast": "", "altitude": "", "notes": "Floral · Sweet · Chocolatey",
        "brew": "v60,aeropress,french_press",
        "description": "A tour of the three flavour families of specialty coffee: the floral Ethiopia Sidamo, the sweet and balanced Colombia Huila and the chocolatey Brazil Cerrado, 100 g of each in a recyclable gift box with a tasting card and brew guide. Choose whole bean or ground for filter.",
        "highlights": ["Three contrasting origins, 300 g in total", "Comes gift-boxed with a tasting card", "Ideal for new pour-over owners", "Save €5 versus buying separately"],
        "brew_guide": ["Taste all three side by side, brewed the same way, to learn what you like.", "Start with the Brazil, then the Colombia, finishing with the Ethiopia."],
        "story": "",
        "story_image": "",
        "images": [("photo-1690983326555-8b8e27843a32", "Scoop of roasted coffee beans next to a burlap sack"), ("photo-1497935586351-b67a49e012bf", "Coffee beans and grounds on wooden boards")],
        "variants": [("W", "Whole bean", 1, {"grind": "whole"}), ("G", "Ground for filter", 1, {"grind": "ground"})],
    },
    {
        "sku": "SM-GFT-BAR", "name": "Home Barista Gift Set", "category": "drip-bags-gifts", "kind": "BUNDLE", "featured": False,
        "short": "A Norrgrind hand grinder, 250 g of Morning Ridge and a wooden scoop, boxed and ready to give.",
        "price": "79.00", "compare_at": "92.50", "cost": "41.00", "stock": 22,
        "origin": "", "brew": "espresso,v60,french_press,moka",
        "description": "Everything a new home barista needs on day one: our compact Norrgrind hand grinder with stepped ceramic burrs, a 250 g bag of Morning Ridge espresso blend roasted that week, and a beech-wood coffee scoop, presented in a kraft gift box on a bed of wood wool.",
        "highlights": ["Grinder, coffee and scoop in one gift", "Saves €13.50 versus buying separately", "Coffee is roasted the week the gift ships", "Add a handwritten note at checkout"],
        "brew_guide": [],
        "story": "",
        "specs": {"Grinder": "Norrgrind Compact, 38 mm ceramic burrs", "Coffee": "250 g Morning Ridge Espresso Blend", "Scoop": "Beech wood, 10 g", "Box": "Recyclable kraft, 28 × 20 × 9 cm"},
        "images": [("photo-1573068012813-e4c7558d8765", "Gift box with a hand grinder, coffee beans and a wooden spoon"), ("photo-1573066380308-24ff4c273dbc", "Wooden hand coffee grinder")],
        "variants": [("STD", "Gift set", 1, {})],
    },
    # ------------------------------------------------------------------ subscriptions
    {
        "sku": "SM-SUB-FIL", "name": "Filter Coffee Subscription", "category": "subscriptions", "kind": "SUBSCRIPTION", "featured": True,
        "short": "A rotating single origin for pour-over, roasted and shipped on your schedule. Pause any time.",
        "price": "14.00", "cost": "6.50", "stock": 999,
        "origin": "Rotating", "brew": "v60,chemex,aeropress,batch", "roast": "LIGHT", "notes": "Changes every delivery",
        "description": "Every delivery brings a different single origin from our filter range — the coffee our roasters are most excited about that month — with a card explaining the farm and a recipe. Choose whole bean or ground, 250 g or 500 g, every two or four weeks. Free shipping on every delivery; pause, skip or cancel from your account.",
        "highlights": ["A new origin every delivery, chosen by the roastery", "Always roasted within 48 hours of dispatch", "Free shipping included in the price", "Pause, skip or cancel any time"],
        "brew_guide": ["Each bag comes with a recipe card tuned to that coffee."],
        "story": "Subscribers get first pick of our smallest lots, often before they reach the webshop. The price you see is per delivery; we charge you when each bag is roasted.",
        "story_image": "photo-1748895177768-b4a54b9c2954",
        "images": [("photo-1748895177768-b4a54b9c2954", "Pour-over kettle, dripper, grinder and cups on a wooden table"), ("photo-1770579673855-ab18aabe71a2", "Coffee brewing equipment on a counter")],
        "variants": [("250-4W", "250 g every 4 weeks", 1, {"weight_g": 250, "interval_weeks": 4}), ("250-2W", "250 g every 2 weeks", 1, {"weight_g": 250, "interval_weeks": 2}), ("500-4W", "500 g every 4 weeks", 1.85, {"weight_g": 500, "interval_weeks": 4})],
    },
    {
        "sku": "SM-SUB-ESP", "name": "Espresso Subscription", "category": "subscriptions", "kind": "SUBSCRIPTION", "featured": False,
        "short": "Morning Ridge, or a rotating single-origin espresso, delivered fresh every two or four weeks.",
        "price": "12.50", "cost": "5.60", "stock": 999,
        "origin": "Rotating", "brew": "espresso,moka", "roast": "MEDIUM", "notes": "Chocolate-forward",
        "description": "Never run out of espresso again. Pick the house blend for consistency, or the roaster's choice for a rotating single-origin espresso. Each bag is rested for ten days before it ships, so it arrives ready to dial in.",
        "highlights": ["House blend or rotating single origin", "Rested for ten days — arrives ready to pull", "Free shipping, every time", "Change grind, size or rhythm from your account"],
        "brew_guide": ["Start at 18 g in, 38 g out, 28 seconds — then adjust."],
        "story": "",
        "story_image": "photo-1574377727482-e82003fd3609",
        "images": [("photo-1574377727482-e82003fd3609", "Espresso pouring into two glasses"), ("photo-1655933143757-cb624d6ba031", "Cup of espresso on a saucer from above")],
        "variants": [("HB-4W", "House blend · 250 g every 4 weeks", 1, {"choice": "house", "interval_weeks": 4}), ("HB-2W", "House blend · 250 g every 2 weeks", 1, {"choice": "house", "interval_weeks": 2}), ("RC-4W", "Roaster's choice · 250 g every 4 weeks", 1.2, {"choice": "rotating", "interval_weeks": 4}), ("KG-4W", "House blend · 1 kg every 4 weeks", 3.2, {"choice": "house", "interval_weeks": 4, "weight_g": 1000})],
    },
    # ------------------------------------------------------------------ equipment
    {
        "sku": "TV-DRP-02", "name": "Tolva Ceramic Dripper 02", "category": "equipment", "kind": "EQUIPMENT", "brand": "tolva", "featured": True,
        "short": "A classic cone dripper in glazed ceramic, sized for one or two cups. Takes standard 02 filters.",
        "price": "24.00", "cost": "10.50", "stock": 48,
        "brew": "v60",
        "description": "The dripper we brew on every morning. Thick Portuguese stoneware holds heat through the brew, spiral ribs keep the paper off the wall for an even flow, and the wide drain hole lets you control the pace with your pour. Compatible with all cone-shaped 02 paper filters. Dishwasher safe.",
        "highlights": ["Heat-retaining glazed stoneware", "Spiral ribs for an even, controllable flow", "Takes any standard 02 cone filter", "Made in Portugal, dishwasher safe"],
        "brew_guide": ["Rinse the paper filter with hot water to pre-heat the ceramic.", "15 g of coffee to 250 g of water is a good starting ratio.", "Pour in slow circles and keep the bed level."],
        "story": "",
        "specs": {"Material": "Glazed stoneware", "Capacity": "1–4 cups (up to 600 ml)", "Filter": "Cone 02 paper filters", "Dimensions": "Ø 12 cm × 9 cm", "Weight": "390 g", "Care": "Dishwasher safe"},
        "images": [("photo-1545665613-29394cee622b", "Ceramic cone dripper brewing onto a glass server"), ("photo-1516510516159-156347b3cf2b", "Top view of a cone dripper with ground coffee"), ("photo-1676600475896-dbf8ddd44f1d", "Dripper on a brewing scale")],
        "variants": [("CRM", "Cream", 1, {"colour": "Cream"}), ("CHR", "Charcoal", 1, {"colour": "Charcoal"})],
    },
    {
        "sku": "TV-SRV-600", "name": "Tolva Glass Server 600 ml", "category": "equipment", "kind": "EQUIPMENT", "brand": "tolva", "featured": False,
        "short": "Heat-resistant borosilicate server with an easy-pour spout and volume marks, 600 ml.",
        "price": "29.00", "cost": "12.00", "stock": 35,
        "brew": "v60,chemex",
        "description": "Brew straight into it, swirl, and pour without drips. The server is blown from borosilicate glass that copes with boiling water and the dishwasher, has subtle 1–4 cup marks, and a lid that doubles as a dripper stand. Fits our Dripper 02 and most other cone drippers.",
        "highlights": ["Borosilicate glass, heat and dishwasher safe", "Drip-free spout and cup marks", "Lid doubles as a dripper stand", "Sized for one big mug or two cups"],
        "brew_guide": [],
        "story": "",
        "specs": {"Material": "Borosilicate glass, silicone lid", "Capacity": "600 ml", "Dimensions": "Ø 11 cm × 14 cm", "Weight": "310 g", "Care": "Dishwasher safe"},
        "images": [("photo-1636903696124-649c068a69c9", "Glass coffee server with a yellow cup outdoors"), ("photo-1609213766164-61ce4ab825f0", "Glass server on a wooden tray")],
        "variants": [("STD", "600 ml", 1, {})],
    },
    {
        "sku": "NG-HG-COMP", "name": "Norrgrind Compact Hand Grinder", "category": "equipment", "kind": "EQUIPMENT", "brand": "norrgrind", "featured": True,
        "short": "Stepped ceramic burrs, 25 g capacity and a fold-flat handle — the travel grinder we recommend most.",
        "price": "69.00", "compare_at": "79.00", "cost": "31.00", "stock": 40,
        "brew": "v60,aeropress,french_press,moka",
        "description": "A hand grinder that actually grinds evenly. The Compact uses 38 mm conical ceramic burrs on a dual-bearing shaft, with 24 clicks of adjustment from Turkish-fine to press-coarse. Twenty-five grams fits a big pour-over; the whole thing fits in a jacket pocket. Grinding a dose for a V60 takes about 40 seconds.",
        "highlights": ["Dual-bearing shaft for consistent particle size", "24-click stepped adjustment", "Fits inside an AeroPress for travel", "Two-year warranty, replaceable burrs"],
        "brew_guide": ["Start at 12 clicks for V60, 8 for AeroPress, 18 for French press."],
        "story": "",
        "specs": {"Burrs": "38 mm conical ceramic", "Capacity": "25 g", "Adjustment": "24 stepped clicks", "Body": "Aluminium, silicone grip", "Weight": "410 g", "Warranty": "2 years"},
        "images": [("photo-1573066380308-24ff4c273dbc", "Manual coffee grinder on a wooden table"), ("photo-1611829371108-544962e333af", "Wooden hand grinder on a bed of coffee beans")],
        "variants": [("STD", "Compact", 1, {})],
    },
    {
        "sku": "NG-EG-HOME", "name": "Norrgrind Home Electric Burr Grinder", "category": "equipment", "kind": "EQUIPMENT", "brand": "norrgrind", "featured": False,
        "short": "A quiet, 40 mm flat-burr grinder with 60 settings that covers espresso to French press.",
        "price": "189.00", "cost": "96.00", "stock": 14,
        "brew": "espresso,v60,french_press,moka,batch",
        "description": "One grinder for everything on the counter. Forty-millimetre hardened-steel flat burrs and a slow 160 rpm motor keep the grind cool and quiet, while the 60-step dial spans true espresso to coarse press. Grind by time or straight into a portafilter with the included fork. Low retention, easy to clean.",
        "highlights": ["40 mm flat steel burrs, 160 rpm for cool grinding", "60 settings from espresso to French press", "Timed dosing plus portafilter fork", "Under 70 dB — quieter than a kettle"],
        "brew_guide": ["Espresso: settings 8–18. Pour-over: 28–38. French press: 45–55."],
        "story": "",
        "specs": {"Burrs": "40 mm flat, hardened steel", "Settings": "60 stepped", "Motor": "160 rpm, 100 W", "Hopper": "250 g", "Dimensions": "13 × 19 × 32 cm", "Warranty": "2 years"},
        "images": [("photo-1461988279488-1dac181a78f9", "Two black electric coffee grinders on a counter"), ("photo-1629248990514-c350da4e7bc9", "Portafilter filled with freshly ground coffee")],
        "variants": [("BLK", "Matte black", 1, {"colour": "Black"})],
    },
    {
        "sku": "TV-KTL-09", "name": "Tolva Gooseneck Kettle 0.9 L", "category": "equipment", "kind": "EQUIPMENT", "brand": "tolva", "featured": False,
        "short": "Precise gooseneck spout, counter-balanced handle and a built-in thermometer. Stovetop and induction.",
        "price": "59.00", "cost": "26.00", "stock": 26,
        "brew": "v60,chemex,aeropress",
        "description": "The slow, controlled pour that pour-over rewards starts with the kettle. Tolva's 0.9-litre gooseneck has a narrow spout for a steady thin stream, a handle that balances the weight of the water, and a lid thermometer so you can hit 92–96 °C without guessing. Works on gas, electric and induction.",
        "highlights": ["Thin, steady stream for controlled pours", "Built-in lid thermometer", "Stovetop and induction compatible", "Brushed stainless steel, 0.9 L"],
        "brew_guide": ["For light roasts heat to 94–96 °C; for medium roasts 90–93 °C."],
        "story": "",
        "specs": {"Material": "304 stainless steel", "Capacity": "0.9 L", "Compatible": "Gas, electric, induction", "Weight": "620 g", "Care": "Hand wash"},
        "images": [("photo-1621745147794-843ab24c3b05", "Black gooseneck kettle on a wooden table"), ("photo-1768674150917-55b1ddf46a02", "Stainless steel gooseneck kettle on a wooden board"), ("photo-1650940925927-f4a30c930a4d", "Black kettle beside a window")],
        "variants": [("BLK", "Matte black", 1, {"colour": "Black"}), ("STL", "Brushed steel", 1, {"colour": "Steel"})],
    },
    {
        "sku": "KC-MUG-300", "age_days": 30, "name": "Kiln & Clay Stoneware Mug 300 ml", "category": "equipment", "kind": "EQUIPMENT", "brand": "kiln-clay", "featured": True,
        "short": "A hand-glazed stoneware mug with a generous handle. Each one is slightly different.",
        "price": "18.00", "cost": "7.50", "stock": 64,
        "brew": "",
        "description": "Thrown and glazed by hand in a small workshop in Girona, this 300 ml mug has a thick wall that keeps coffee warm and a handle that fits three fingers. The reactive glaze means no two are identical. Dishwasher and microwave safe.",
        "highlights": ["Hand-thrown stoneware, reactive glaze", "Keeps coffee warm longer than thin porcelain", "Dishwasher and microwave safe", "Three colours that match our drippers"],
        "brew_guide": [],
        "story": "",
        "specs": {"Material": "Stoneware, lead-free glaze", "Capacity": "300 ml", "Dimensions": "Ø 8.5 cm × 9.5 cm", "Weight": "340 g", "Care": "Dishwasher and microwave safe"},
        "images": [("photo-1495100497150-fe209c585f50", "Speckled stoneware mug on a wooden table"), ("photo-1552010266-6458fda4d692", "Stoneware mug of coffee from above"), ("photo-1563696629964-8c3ce077cf3e", "Handmade mugs on a wooden rack")],
        "variants": [("OAT", "Oat", 1, {"colour": "Oat"}), ("MOSS", "Moss", 1, {"colour": "Moss"}), ("TERRA", "Terracotta", 1, {"colour": "Terracotta"})],
    },
    {
        "sku": "TV-FLT-02", "name": "Tolva Paper Filters 02 (100 pcs)", "category": "equipment", "kind": "EQUIPMENT", "brand": "tolva", "featured": False,
        "short": "Oxygen-bleached cone filters for 02 drippers. No paper taste, even flow, 100 per box.",
        "price": "6.50", "cost": "2.40", "stock": 300,
        "brew": "v60",
        "description": "Cone filters that fit our Dripper 02 and every other 02-size cone. Oxygen bleached so there is no papery taste, with a crepe texture that keeps flow consistent from the first cup to the last. Compostable.",
        "highlights": ["Fits all 02 cone drippers", "Oxygen bleached — no paper taste", "Compostable", "100 filters per box"],
        "brew_guide": ["Always rinse the filter with hot water before brewing."],
        "story": "",
        "specs": {"Size": "02 (1–4 cups)", "Quantity": "100", "Material": "Oxygen-bleached paper", "Compostable": "Yes"},
        "images": [("photo-1504469089401-14f795f6ddee", "Paper filter in a dripper with a kettle pouring"), ("photo-1517224187585-e3016a5fddc8", "Pouring water onto a coffee filter")],
        "variants": [("100", "Box of 100", 1, {}), ("300", "3 boxes (300)", 2.7, {})],
    },
    # ------------------------------------------------------------------ coming soon (draft, admin demo)
    {
        "sku": "SM-PAN-GEI", "age_days": 1, "name": "Panama Boquete Geisha", "category": "filter-coffee", "kind": "COFFEE", "featured": False, "status": "DRAFT",
        "short": "A washed Geisha from Boquete — jasmine, lychee and white peach. Landing in autumn.",
        "price": "38.00", "cost": "19.00", "stock": 0,
        "origin": "Panama", "region": "Boquete, Chiriquí", "producer": "Finca Alto Quiel", "variety": "Geisha",
        "process": "WASHED", "roast": "LIGHT", "altitude": "1,800–1,950 m", "notes": "Jasmine, lychee, white peach",
        "brew": "v60,chemex",
        "description": "Our first Geisha release. Pre-orders open in September.",
        "highlights": ["Competition-grade Geisha", "100 g bags only"],
        "brew_guide": [],
        "story": "",
        "images": [("photo-1677125671399-65852c6dfb05", "Coffee cherries ripening on the branch")],
        "variants": [("100W", "100 g · Whole bean", 1, {"weight_g": 100, "grind": "whole"})],
    },
]

# (first name, last name, city)
REVIEWERS = [
    ("Marta", "Iglesias", "Valencia"), ("Tomás", "Ferreira", "Lisbon"), ("Lena", "Hoffmann", "Berlin"), ("Julien", "Morel", "Lyon"),
    ("Ana", "Costa", "Porto"), ("Pieter", "de Vries", "Utrecht"), ("Sofia", "Bianchi", "Milan"), ("Kasia", "Nowak", "Kraków"),
    ("Diego", "Romero", "Madrid"), ("Eimear", "Walsh", "Dublin"), ("Noah", "Lindqvist", "Malmö"), ("Clara", "Vidal", "Barcelona"),
]

# sku -> list of (reviewer index, rating, days ago, comment)
REVIEWS = {
    "SM-ETH-SID": [(0, 5, 6, "Brewed on a V60 following the card. Jasmine straight away, and the peach note really shows up as it cools. My favourite coffee of the year."),
                   (3, 5, 19, "Incroyable. Tea-like and delicate; nothing like the 'bright' coffees that are just sour."),
                   (7, 4, 41, "Beautiful coffee, but needs a good grinder — with my blade grinder it was a bit thin. Upgraded, problem solved.")],
    "SM-COL-HUI": [(1, 5, 3, "The one I keep re-ordering. Sweet, clean, zero fuss in the AeroPress at work."),
                   (4, 5, 12, "Roast date was four days before delivery. Caramel and apple exactly as described."),
                   (8, 4, 27, "Very good everyday coffee. Would love a 500 g option."),
                   (10, 5, 55, "Bought it for the office batch brewer and now everyone asks where it is from.")],
    "SM-KEN-NYE": [(2, 5, 9, "Blackcurrant bomb. Intense, juicy, wonderful. Grab it before it goes."),
                   (5, 4, 33, "Fantastic in the Chemex. A touch too bright for my partner, perfect for me.")],
    "SM-GUA-HUE": [(6, 4, 15, "Comforting and chocolatey, great with a splash of oat milk."),
                   (11, 5, 48, "Our house French press coffee now. Smooth, sweet, no bitterness.")],
    "SM-CRI-TAR": [(0, 5, 21, "Made cold brew with it for a week — honey and red grape, ridiculously sweet."),
                   (9, 5, 38, "The sweetest coffee I have had from a pour-over. The micro-mill story on the card was a nice touch.")],
    "SM-RWA-NYA": [(3, 4, 30, "Elegant, floral, a little lighter in body than the Ethiopia. Lovely with breakfast.")],
    "SM-BRA-CER": [(8, 5, 8, "Hazelnut and chocolate, easy in the moka pot. Best value here by far."),
                   (1, 4, 44, "Solid, sweet, low acidity. Good as espresso too.")],
    "SM-ESP-MRG": [(11, 5, 2, "Dialled in on a home machine in two shots: 18 g in, 39 g out, 29 s. Chocolate, hazelnut, sweet in milk. House blend for life."),
                   (5, 5, 17, "Finally an espresso that is forgiving. Flat whites taste like a proper café."),
                   (2, 4, 29, "Very good and consistent across three bags. A bit classic for my taste, but that is the point."),
                   (9, 5, 61, "Bought the 1 kg, it rested for two weeks and just got better."),
                   (6, 5, 80, "Our café trialled it for a month and switched.")],
    "SM-ESP-MDH": [(4, 5, 11, "Dark without being burnt — exactly as promised. Brilliant in the moka pot."),
                   (7, 4, 52, "Strong, chocolatey, great with milk. Slightly heavy as a straight shot.")],
    "SM-ETH-GUJ": [(10, 5, 14, "Blueberries. Actual blueberries. As an Americano it is unreal.")],
    "SM-COL-DEC": [(0, 5, 5, "Nobody at dinner guessed it was decaf. Toffee and apple, clean finish."),
                   (6, 4, 36, "Best decaf I have found in Europe. Works fine as espresso as well."),
                   (3, 5, 70, "Evening coffee solved.")],
    "SM-MEX-DEC": [(1, 4, 24, "Nutty and smooth in the French press. Good decaf for milk drinks.")],
    "SM-DRP-BOX": [(2, 5, 7, "Took them hiking — hot water from a flask, and it tasted like proper pour-over. Genius."),
                   (8, 4, 40, "Great for hotel rooms. Wish the box of 30 came in a mixed selection.")],
    "SM-GFT-TRIO": [(9, 5, 10, "Gave this to my dad with a V60 and he has since ordered the Ethiopia twice. The tasting card is a great idea."),
                    (5, 5, 47, "Beautiful box, three very different coffees. Perfect gift.")],
    "SM-GFT-BAR": [(7, 5, 26, "Gifted to a colleague who had just bought an espresso machine — grinder is surprisingly capable.")],
    "SM-SUB-FIL": [(4, 5, 4, "Third delivery and each coffee has been a surprise — the Rwanda last month was my favourite. Pausing for holidays was one click."),
                   (11, 5, 35, "Roast date always within a few days. Exactly what a subscription should be.")],
    "SM-SUB-ESP": [(6, 4, 20, "Reliable and fresh. Would like to be able to mix house blend and roaster's choice.")],
    "TV-DRP-02": [(0, 5, 13, "Heavy, well glazed, drains evenly. Replaced my plastic dripper and the cups are noticeably sweeter."),
                  (10, 4, 58, "Lovely dripper. Charcoal colour looks great next to the server.")],
    "TV-SRV-600": [(2, 5, 22, "Pours without a single drip. Fits the dripper perfectly.")],
    "NG-HG-COMP": [(1, 5, 16, "Grinds a V60 dose in about 40 seconds, even particle size, fits in the AeroPress. Great for travel."),
                   (8, 4, 45, "Good grinder for the price. Coarse settings a bit less consistent than fine, as with all hand grinders.")],
    "NG-EG-HOME": [(11, 5, 31, "Quiet, fast and the espresso range is genuinely usable. Low retention is true — maybe 0.2 g.")],
    "TV-KTL-09": [(3, 5, 18, "The thermometer alone made my pour-overs better. Steady thin stream, balanced handle."),
                  (9, 4, 63, "Works on induction as promised. Lid thermometer is a bit slow to react.")],
    "KC-MUG-300": [(5, 5, 9, "Gorgeous glaze, keeps coffee warm, fits my hand. Bought the moss one and went back for oat."),
                   (7, 5, 50, "Each one is slightly different and that is the charm.")],
    "TV-FLT-02": [(4, 4, 28, "No paper taste after a rinse. Flow is consistent. Does what it should.")],
}


# --- Segmentation dimensions -------------------------------------------------------------------
# Subcategories give the catalogue a second level to drill into; the storefront already treats a
# parent category as "itself plus its children", so nothing in the navigation changes.
SUBCATEGORIES = [
    ("africa", "Africa", "filter-coffee", "Ethiopia, Kenya, Rwanda and Burundi lots.", 1),
    ("latin-america", "Latin America", "filter-coffee", "Colombia, Brazil, Costa Rica, Guatemala and Peru.", 2),
    ("asia-pacific", "Asia Pacific", "filter-coffee", "Indonesia, India and Papua New Guinea.", 3),
    ("espresso-blends", "Espresso Blends", "espresso", "House blends built for milk and for black.", 1),
    ("espresso-single-origin", "Single Origin Espresso", "espresso", "Seasonal lots roasted for the machine.", 2),
    ("brewers", "Brewers & Drippers", "equipment", "V60s, Chemex, AeroPress and the servers that go with them.", 1),
    ("grinders-kettles", "Grinders & Kettles", "equipment", "Burr grinders and pouring kettles.", 2),
    ("mugs-accessories", "Mugs & Accessories", "equipment", "Cups, scales, filters and cleaning kit.", 3),
]

# (slug, name, group, description) — tags overlap, unlike categories.
TAGS = [
    ("gift", "Gift", "OCCASION", "Sells hard in November and December."),
    ("everyday", "Everyday", "AUDIENCE", "The bags people re-order without thinking."),
    ("beginner-friendly", "Beginner friendly", "AUDIENCE", "Forgiving recipes, approachable flavours."),
    ("enthusiast", "Enthusiast", "AUDIENCE", "For people who weigh their water."),
    ("limited", "Limited lot", "MERCHANDISING", "Micro-lots that are not restocked."),
    ("high-margin", "High margin", "MERCHANDISING", "Above-average contribution per unit."),
    ("bestseller", "Bestseller", "MERCHANDISING", "Top of the sales ranking."),
    ("decaf", "Decaf", "ATTRIBUTE", "No caffeine, same care."),
    ("fruity", "Fruity", "ATTRIBUTE", "Berry, stone fruit and citrus notes."),
    ("chocolatey", "Chocolatey", "ATTRIBUTE", "Cocoa, nut and caramel notes."),
    ("summer", "Summer", "OCCASION", "Iced and cold-brew friendly."),
    ("subscription-friendly", "Subscription friendly", "MERCHANDISING", "Common choice for a recurring plan."),
]

# Campaigns get a reporting bucket, an objective and a target market so media analysis has dimensions.
CAMPAIGNS = [
    ("Google Search Always On", "google", "cpc", "brand_exact", "Paid Search", "ACQUISITION", 4200, "", ""),
    ("Google Shopping Feed", "google", "cpc", "shopping_feed", "Paid Search", "ACQUISITION", 2600, "", ""),
    ("Meta Prospecting", "meta", "paid_social", "always_on_prospecting", "Paid Social", "ACQUISITION", 3800, "", ""),
    ("Meta Retargeting", "meta", "paid_social", "retargeting_dynamic", "Paid Social", "RETENTION", 1400, "", ""),
    ("Weekly Roast Note", "newsletter", "email", "weekly_roast_note", "Email", "RETENTION", 900, "", ""),
    ("Winback 90 Days", "newsletter", "email", "winback_90d", "Email", "WINBACK", 450, "", ""),
    ("Partner Blogs", "partner", "referral", "blog_partnerships", "Referral", "BRAND", 600, "", ""),
    ("Affiliate Network Q3", "affiliate", "affiliate", "affiliate_network_q3", "Affiliate", "ACQUISITION", 1100, "", ""),
    ("DACH Launch Push", "meta", "paid_social", "dach_launch", "Paid Social", "ACQUISITION", 1800, "DACH", "DE"),
    ("Black Friday Social", "meta", "paid_social", "black_friday_social", "Paid Social", "PROMOTION", 2900, "", ""),
]

# (code, kind, value, minimum, channel, first_order_only, campaign utm, description)
DISCOUNTS = [
    ("WELCOME10", "PERCENT", 10, 20, "email", True, "welcome_flow", "10% off a first order over EUR 20"),
    ("BREWGEAR5", "FIXED", 5, 50, "site", False, "", "EUR 5 off brewing equipment orders over EUR 50"),
    ("SUBSCRIBE15", "PERCENT", 15, 0, "email", False, "subscriber_only_drop", "Subscriber-only drop discount"),
    ("BLACKFRIDAY20", "PERCENT", 20, 40, "paid_social", False, "black_friday_social", "Seasonal promotion"),
    ("FREIGHTFREE", "FREE_SHIPPING", 0, 25, "site", False, "", "Free delivery over EUR 25"),
    ("CAFE25", "PERCENT", 25, 150, "sales", False, "", "Wholesale and cafe accounts"),
    ("COMEBACK12", "PERCENT", 12, 25, "email", False, "winback_90d", "Winback offer for lapsed customers"),
    ("PARTNER10", "PERCENT", 10, 30, "influencer", False, "blog_partnerships", "Partner and creator code"),
]
