# Generated by Django 4.2.1 on 2026-08-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Created automatically by guest checkout; has no password.'),
        ),
    ]
