# Generated by Django 4.2.1 on 2026-09-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('accounts', '0003_coffee_storefront'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, max_length=40)),
                ('old_value', models.CharField(blank=True, max_length=40)),
                ('new_value', models.CharField(blank=True, max_length=40)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('changed_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'customer segment history',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='acquisition_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='acquisition_channel_group',
            field=models.CharField(blank=True, db_index=True, help_text='Reporting bucket, e.g. Paid Search, Paid Social, Organic, Email.', max_length=40),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='acquisition_medium',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2.', max_length=2),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='default_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, help_text='First session, which may predate registration.', null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False, help_text='Row created by the admin test-data generator; never real business data.'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='landing_page',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last session or order seen for this customer.', null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='lifecycle_stage',
            field=models.CharField(blank=True, choices=[('LEAD', 'Lead'), ('NEW', 'New customer'), ('ACTIVE', 'Active'), ('AT_RISK', 'At risk'), ('DORMANT', 'Dormant'), ('CHURNED', 'Churned')], db_index=True, help_text='Maintained by the CRM sync; may lag behind the order history.', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='loyalty_tier',
            field=models.CharField(blank=True, choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='market',
            field=models.CharField(blank=True, db_index=True, help_text='Commercial grouping used by the sales team, e.g. Iberia, DACH, Nordics.', max_length=40),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='marketing_opt_in',
            field=models.BooleanField(blank=True, help_text='NULL when the visitor never answered.', null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='referrer_domain',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='region',
            field=models.CharField(blank=True, help_text='State / province / autonomous community.', max_length=80),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='segment',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('HORECA', 'Cafe / restaurant'), ('WHOLESALE', 'Wholesale'), ('CORPORATE', 'Corporate gifting')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='signup_device',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='test_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='analytics.testdatabatch'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='timezone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Double opt-in confirmation; NULL when never confirmed.', null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='medium',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='acquisition_source',
            field=models.CharField(db_index=True, default='direct', max_length=40),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['segment', 'lifecycle_stage'], name='accounts_profile_seg_idx'),
        ),
        migrations.AddField(
            model_name='customersegmenthistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_history', to='accounts.customerprofile'),
        ),
    ]
