# Generated by Django 4.2.1 on 2026-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-changed_at'], 'verbose_name_plural': 'price history'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-primary', 'position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'status'], name='catalog_product_visible_idx'),
        ),
    ]
