# Generated by Django 4.2.1 on 2026-08-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mvp_storefront'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
