# Generated by Django 4.2.1 on 2026-08-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_guest_and_uploads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Used when no image file is uploaded.'),
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the navigation.'),
        ),
        migrations.AddField(
            model_name='product',
            name='altitude',
            field=models.CharField(blank=True, help_text='e.g. 1,900–2,100 m', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='brew_guide',
            field=models.TextField(blank=True, help_text='Recipe steps — one per line.'),
        ),
        migrations.AddField(
            model_name='product',
            name='brew_methods',
            field=models.CharField(blank=True, help_text='Comma separated codes: v60, chemex, aeropress, french_press, espresso, moka, cold_brew, batch', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previous / list price; when higher than the sale price a discount badge is shown.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Shown in the home page best-sellers section.'),
        ),
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.TextField(blank=True, help_text="'Why you'll love it' bullets — one per line."),
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('COFFEE', 'Coffee'), ('EQUIPMENT', 'Brewing equipment'), ('BUNDLE', 'Gift box / bundle'), ('SUBSCRIPTION', 'Subscription')], default='COFFEE', help_text='Controls which product-page sections are shown.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, help_text="Country, e.g. Ethiopia. Blends: 'Brazil, Colombia'.", max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_story',
            field=models.TextField(blank=True, help_text='Editorial paragraph(s) about the origin / maker.'),
        ),
        migrations.AddField(
            model_name='product',
            name='process',
            field=models.CharField(blank=True, choices=[('WASHED', 'Washed'), ('NATURAL', 'Natural'), ('HONEY', 'Honey'), ('ANAEROBIC', 'Anaerobic'), ('DECAF_EA', 'Sugarcane EA decaf'), ('DECAF_SWP', 'Swiss Water decaf')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, help_text='Farm, washing station or cooperative.', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('LIGHT', 'Light'), ('MEDIUM_LIGHT', 'Medium-light'), ('MEDIUM', 'Medium'), ('MEDIUM_DARK', 'Medium-dark'), ('DARK', 'Dark')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='One sentence shown under the title and on cards.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Equipment specifications, e.g. {"Material": "Ceramic"}.'),
        ),
        migrations.AddField(
            model_name='product',
            name='story_image_url',
            field=models.URLField(blank=True, help_text='Large lifestyle image for the story section.'),
        ),
        migrations.AddField(
            model_name='product',
            name='tasting_notes',
            field=models.CharField(blank=True, help_text='Comma separated, e.g. Jasmine, bergamot, peach', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
