# Generated by Django 4.2.1 on 2026-09-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_guest_split_payments'),
        ('catalog', '0004_coffee_storefront'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('group', models.CharField(choices=[('MERCHANDISING', 'Merchandising'), ('AUDIENCE', 'Audience'), ('OCCASION', 'Occasion'), ('ATTRIBUTE', 'Attribute')], db_index=True, default='MERCHANDISING', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='discontinued_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=False, help_text='Micro-lot or one-off release that is not restocked.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='launched_at',
            field=models.DateField(blank=True, help_text='First day on sale; NULL for products migrated from the old shop.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_country_code',
            field=models.CharField(blank=True, db_index=True, help_text='ISO code of the growing country; blank for blends and equipment.', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Net weight of the base unit; NULL for subscriptions.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='channel',
            field=models.CharField(choices=[('WEB', 'Website form'), ('EMAIL', 'Post-purchase e-mail'), ('SUPPORT', 'Collected by support'), ('IMPORT', 'Imported from the old shop')], db_index=True, default='WEB', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Set when the review was collected after a known purchase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='sales.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the shop replied; NULL when never answered.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='ProductStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'product status history',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tag'),
        ),
    ]
