# Generated by Django 4.2.1 on 2026-09-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_tag_product_discontinued_at_product_is_limited_and_more'),
        ('analytics', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0, help_text='As reported by the ad platform, which does not always agree with the shop database.')),
            ],
            options={
                'ordering': ['-date', 'campaign_id'],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('physical', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('incoming', models.PositiveIntegerField(default=0)),
                ('damaged', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost price on that date; multiply by physical for stock value.', max_digits=12)),
            ],
            options={
                'ordering': ['-snapshot_date', 'warehouse_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productevent',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Planned budget; compare with the spend actually booked in campaign metrics.', max_digits=14),
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel_group',
            field=models.CharField(blank=True, db_index=True, help_text='Paid Search, Paid Social, Email, Affiliate, Display…', max_length=40),
        ),
        migrations.AddField(
            model_name='campaign',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='campaign',
            name='objective',
            field=models.CharField(choices=[('ACQUISITION', 'Acquisition'), ('RETENTION', 'Retention'), ('BRAND', 'Brand'), ('PROMOTION', 'Promotion'), ('WINBACK', 'Winback')], default='ACQUISITION', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished')], db_index=True, default='RUNNING', max_length=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_market',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productevent',
            name='browser',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productevent',
            name='channel_group',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productevent',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productevent',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='productevent',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productevent',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False, help_text='Row created by the admin test-data generator; never real business data.'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='landing_page',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productevent',
            name='market',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productevent',
            name='medium',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productevent',
            name='os',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productevent',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productevent',
            name='referrer_domain',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productevent',
            name='region',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productevent',
            name='results_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productevent',
            name='search_term',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productevent',
            name='test_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.testdatabatch'),
        ),
        migrations.AddField(
            model_name='productevent',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productevent',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value attached to the event, when there is one.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productevent',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract_started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='reason',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='transfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='market',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='opened_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='region',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='timezone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='source',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='kind',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('SHIP', 'Ship'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('ADJUST', 'Adjust'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='device',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='kind',
            field=models.CharField(choices=[('SESSION_STARTED', 'Session'), ('PRODUCT_VIEWED', 'View'), ('SEARCH_PERFORMED', 'Search'), ('ADD_TO_CART', 'Add'), ('REMOVE_FROM_CART', 'Remove'), ('CHECKOUT_STARTED', 'Checkout'), ('PAYMENT_SUBMITTED', 'Payment'), ('PURCHASE_COMPLETED', 'Purchase'), ('NEWSLETTER_SIGNUP', 'Newsletter'), ('REVIEW_SUBMITTED', 'Review')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='session_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='source',
            field=models.CharField(db_index=True, default='direct', max_length=40),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('PARTIALLY_RECEIVED', 'Partial'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['created_at', 'kind'], name='ops_event_created_kind'),
        ),
        migrations.AddIndex(
            model_name='productevent',
            index=models.Index(fields=['session_id', 'created_at'], name='ops_event_session_idx'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='operations.warehouse'),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='operations.campaign'),
        ),
        migrations.AddConstraint(
            model_name='inventorysnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot_date', 'warehouse', 'variant'), name='unique_inventory_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='campaigndailymetric',
            constraint=models.UniqueConstraint(fields=('campaign', 'date'), name='unique_campaign_day'),
        ),
    ]
