# Generated by Django 4.2.1 on 2026-09-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('operations', '0002_campaigndailymetric_inventorysnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndailymetric',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='campaigndailymetric',
            name='test_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_metrics', to='analytics.testdatabatch'),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='test_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='analytics.testdatabatch'),
        ),
    ]
