# Generated by Django 4.2.1 on 2026-09-01 15:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_campaigndailymetric_inventorysnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_tag_product_discontinued_at_product_is_limited_and_more'),
        ('analytics', '0001_initial'),
        ('sales', '0003_guest_split_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], default='EUR', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12)),
                ('reason', models.CharField(choices=[('RETURN', 'Return'), ('GOODWILL', 'Goodwill'), ('LATE_DELIVERY', 'Late Delivery'), ('DAMAGED_IN_TRANSIT', 'Damaged In Transit'), ('PRICE_ADJUSTMENT', 'Price Adjustment'), ('CANCELLED_ORDER', 'Cancelled Order'), ('DUPLICATE_CHARGE', 'Duplicate Charge')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='SUCCEEDED', max_length=15)),
                ('initiated_by', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPORT', 'Support'), ('SYSTEM', 'System')], default='SUPPORT', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'return history',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(db_index=True, max_length=40)),
                ('service_level', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express'), ('PICKUP_POINT', 'Pickup Point'), ('SAME_DAY', 'Same Day')], default='STANDARD', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('LABEL_CREATED', 'Label Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETURNED_TO_SENDER', 'Returned To Sender'), ('LOST', 'Lost')], db_index=True, default='LABEL_CREATED', max_length=25)),
                ('destination_country_code', models.CharField(blank=True, max_length=2)),
                ('destination_city', models.CharField(blank=True, max_length=80)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='What the carrier charges the shop.', max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], default='EUR', max_length=3)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], db_index=True, default='MONTHLY', max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], default='EUR', max_length=3)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('channel_group', models.CharField(blank=True, max_length=40)),
                ('utm_source', models.CharField(blank=True, max_length=40)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('next_delivery_on', models.DateField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, choices=[('TOO_MUCH_COFFEE', 'Too Much Coffee'), ('PRICE', 'Price'), ('QUALITY', 'Quality'), ('DELIVERY_ISSUES', 'Delivery Issues'), ('MOVED', 'Moved'), ('SWITCHED_ROASTER', 'Switched Roaster'), ('PAYMENT_FAILED', 'Payment Failed'), ('OTHER', 'Other')], help_text='Optional exit-survey answer; frequently left empty.', max_length=30)),
                ('is_test_data', models.BooleanField(db_index=True, default=False, help_text='Row created by the admin test-data generator; never real business data.')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CREATED', 'Created'), ('RENEWED', 'Renewed'), ('SKIPPED', 'Skipped'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('PLAN_CHANGED', 'Plan Changed'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=15)),
                ('to_status', models.CharField(blank=True, max_length=15)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['created_at', 'id'], 'verbose_name_plural': 'order history'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='cart',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, help_text='Set by the cleanup job when a cart was never checked out.', null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='browser',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cart',
            name='channel_group',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cart',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='cart',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='cart',
            name='device',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False, help_text='Row created by the admin test-data generator; never real business data.'),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cart',
            name='test_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='analytics.testdatabatch'),
        ),
        migrations.AddField(
            model_name='cart',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cart',
            name='utm_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='operations.campaign'),
        ),
        migrations.AddField(
            model_name='discount',
            name='channel',
            field=models.CharField(blank=True, help_text='Where the code was distributed: email, influencer, print, support…', max_length=40),
        ),
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], default='EUR', help_text='Only meaningful for FIXED codes.', max_length=3),
        ),
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='discount',
            name='first_order_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='max_per_customer',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='browser',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='operations.campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('PAYMENT_TIMEOUT', 'Payment Timeout'), ('PAYMENT_FAILED', 'Payment Failed'), ('OUT_OF_STOCK', 'Out Of Stock'), ('CUSTOMER_REQUEST', 'Customer Request'), ('SUSPECTED_FRAUD', 'Suspected Fraud'), ('DUPLICATE', 'Duplicate'), ('ADDRESS_INVALID', 'Address Invalid')], max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('WEB', 'Website'), ('MOBILE_WEB', 'Mobile website'), ('PHONE', 'Phone order'), ('MARKETPLACE', 'Marketplace'), ('SUBSCRIPTION', 'Subscription renewal'), ('POS', 'Roastery counter')], db_index=True, default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='channel_group',
            field=models.CharField(blank=True, db_index=True, help_text='Reporting bucket: Paid Search, Paid Social, Organic, Email, Referral, Direct.', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], db_index=True, default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Rate to EUR captured at checkout. total * fx_rate = EUR value.', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_test_data',
            field=models.BooleanField(db_index=True, default=False, help_text='Row created by the admin test-data generator; never real business data.'),
        ),
        migrations.AddField(
            model_name='order',
            name='landing_page',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='market',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='os',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='referrer_domain',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Joins the order to its browsing session in operations_productevent.', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery charged to the customer, included in total.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_region',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='test_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='analytics.testdatabatch'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='actor',
            field=models.CharField(blank=True, help_text='Who caused the change: customer, staff username, system job…', max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order of the line in the basket.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refunded_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT contained in this line after its share of the order discount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 for the first try; retries after a decline increment it.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_code',
            field=models.CharField(blank=True, help_text='Provider decline code, e.g. insufficient_funds, do_not_honor.', max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Processing fee kept by the provider.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CARD', 'Credit / debit card'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay'), ('BANK_TRANSFER', 'Bank transfer'), ('KLARNA', 'Klarna'), ('GIFT_CARD', 'Gift card'), ('COD', 'Cash on delivery')], db_index=True, default='CARD', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='When the money reached the shop account; NULL while in transit.', null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='carrier',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer_comment',
            field=models.TextField(blank=True, help_text='Free text from the return form; often left empty.'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='resolution',
            field=models.CharField(blank=True, choices=[('REFUND', 'Refund'), ('REPLACEMENT', 'Replacement'), ('STORE_CREDIT', 'Store Credit'), ('NONE', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='discount',
            name='kind',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('PERCENT', 'Percent'), ('FREE_SHIPPING', 'Free Shipping')], max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(db_index=True, default='direct', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=24),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('DEFECTIVE', 'Defective'), ('DAMAGED', 'Damaged'), ('WRONG_PRODUCT', 'Wrong'), ('DID_NOT_FIT', 'Fit'), ('CHANGED_MIND', 'Mind'), ('LATE_DELIVERY', 'Late'), ('TASTE_NOT_AS_EXPECTED', 'Taste'), ('STALE_ON_ARRIVAL', 'Stale'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Received'), ('REFUNDED', 'Refunded')], db_index=True, default='REQUESTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status'], name='sales_order_created_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['channel_group', 'created_at'], name='sales_order_channel_idx'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='test_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='analytics.testdatabatch'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.order'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='operations.warehouse'),
        ),
        migrations.AddField(
            model_name='returnhistory',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sales.returnrequest'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='sales.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='sales.returnrequest'),
        ),
        migrations.AddField(
            model_name='discountredemption',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountredemption',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='sales.discount'),
        ),
        migrations.AddField(
            model_name='discountredemption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='sales.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.subscription'),
        ),
    ]
