# Generated by Django 4.2.1 on 2026-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_discountredemption_refund_returnhistory_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], default='EUR', help_text='Only meaningful for FIXED codes.', max_length=3),
        ),
        migrations.AlterField(
            model_name='discountredemption',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], db_index=True, default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='refund',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='refund_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'Pound sterling'), ('CHF', 'Swiss franc'), ('SEK', 'Swedish krona'), ('DKK', 'Danish krone'), ('USD', 'US dollar')], default='EUR', max_length=3),
        ),
    ]
